### ISSUE TITLE
powershell script for Gitlab-runner installation

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9test/plcn#10]
powershell script for Gitlab-runner installation

**Comment by qiaofeng1227** [comment]
Install Gitlab-runner OK，how to install git？

**Comment by qiaofeng1227** [comment]
1. winget install git
you must install winget before， [production version only support app](https://docs.microsoft.com/en-us/windows/package-manager/winget/#production-recommended)
2. Silent installation
https://github.com/dahlbyk/posh-git

**Comment by chendelin1982** [comment]
git have silent install parameter
